# Generated by Django 5.1.5 on 2025-01-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereview',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='product_image/'),
        ),
        migrations.AlterField(
            model_name='storewebsite',
            name='website_name',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Telegram', 'Telegram'), ('Linkedin', 'Linkedin'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter')], max_length=32),
        ),
    ]
