# Generated by Django 5.1.5 on 2025-01-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=1, upload_to='product_image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storewebsite',
            name='website_name',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Telegram', 'Telegram'), ('Linkedin', 'Linkedin'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter')], default=1, max_length=32),
            preserve_default=False,
        ),
    ]
