# Generated by Django 5.1.5 on 2025-01-21 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierrating',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_rating', to='glovo_app.courier'),
        ),
    ]
