# Generated by Django 5.1.5 on 2025-01-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='combo',
            unique_together={('store', 'combo_name')},
        ),
    ]
