# Generated by Django 5.1.5 on 2025-01-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0002_alter_combo_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartcombo',
            old_name='combo_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='cartproduct',
            old_name='product_quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
