# Generated by Django 5.1.5 on 2025-01-20 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0002_storereview_created_date_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='glovo_app.cart'),
        ),
    ]
