# Generated by Django 5.1.5 on 2025-01-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0002_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereview',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
