# Generated by Django 5.1.5 on 2025-01-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0002_category_store_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='category',
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='glovo_app.category'),
        ),
    ]
