# Generated by Django 5.1.5 on 2025-01-20 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0003_alter_cartproduct_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_combo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='glovo_app.cartcombo'),
            preserve_default=False,
        ),
    ]
