# Generated by Django 5.1.5 on 2025-01-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0004_category_category_name_de_category_category_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.ManyToManyField(to='glovo_app.category'),
        ),
    ]
